name: 'Install node module'
description: 'some description'
inputs:
  caching:
    required: false
    description: 'enable caching'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Cache node module
      if: inputs.caching == 'true'
      id: cache-step
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-cache-file-&{{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cache-file-
          ${{ runner.os }}-
    - name: Display cache
      run: echo '${{ toJSON(steps.cache-step.outputs) }}'
      shell: bash
    - name: Install node
      run: |
        npm init
        npm install
      shell: bash


